# This is a basic workflow to help you get started with Actions

name: Windows Package

on: [push, pull_request, workflow_dispatch]

jobs:
  static-build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v6
      - uses: AllanChain/install-qt-static@v6.10.1
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build Project
        run: |
          qt-cmake -Bbuild -DCMAKE_BUILD_TYPE=MinSizeRel .
          cmake --build build -j --config Release
          cmake --install build --config Release --prefix "install"
      - name: Upload
        uses: actions/upload-artifact@v5
        with:
          name: pmidi-win-static-build
          path: "install/bin/"
